# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170408_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
