# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='User',
        ),
    ]
