# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170407_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
